### ISSUE TITLE
Delete torch

### ISSUE THREAD

**Issue by ItayHoresh** [OperationalBina/PipeRT#54]
We need to check if we can get rid of torch.

We are using torch.multiprocessing for running routine as a process.

**Comment by AmitKarin** [comment]
I saw in the code that in the yolov3 component we use [torch_utils](https://github.com/ItamarWilf/PipeRT/blob/master/pipert/contrib/detection_demo/torch_utils.py) with more function from torch. So can we really get rid of it? Or maybe we can take just what we need for this as well?

**Comment by ItayHoresh** [comment]
I don't know for sure if we can get rid of it. The goal is to delete it for creating smaller image.
If we must have in order to run some of our routines there is nothing we can do.
@AmitKarin if you think it's not possible - say so and we will close the issue.

**Comment by AmitKarin** [comment]
@ItayHoresh  I see in the [torch_utils](https://github.com/ItamarWilf/PipeRT/blob/master/pipert/contrib/detection_demo/torch_utils.py) that the yolov3 component use the "select_device" func which can allow to select the CUDA as the device. I don't think we can delete it.

**Comment by ItayHoresh** [comment]
Torch is now optional.
